# Generated by Django 3.2.5 on 2021-12-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patientr',
            new_name='patient',
        ),
    ]
