# Generated by Django 3.2.5 on 2021-12-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
