# Generated by Django 3.2.5 on 2022-05-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auto_20220407_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=50)),
                ('pre', models.ImageField(default='', upload_to='contact/images')),
            ],
        ),
    ]
